# -*- coding: utf-8 -*-
"""
/***************************************************************************
 pluginSAVI
                                 A QGIS plugin
 plugin for SAVI
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-03-02
        copyright            : (C) 2021 by Parkhomchuk_O
        email                : omparkhomchuk@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load pluginSAVI class from file pluginSAVI.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .savi_plugin import pluginSAVI
    return pluginSAVI(iface)
